spring.application.name=Wildberries

spring.datasource.url=jdbc:postgresql://localhost:5432/wildberries
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:V2lsZGJlcnJpZXMtSldULWRldmVsb3BtZW50LXNlY3JldC1rZXktMjAyNg==}
jwt.expiration-ms=3600000

alif-shop.base-url=https://api.alifshop.tj